//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGSolar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Role { get; set; }
        public string ContactNo { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
    }
}
