//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGSolar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Items
    {
        public long itemcode { get; set; }
        public string itemname { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
