//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGSolar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_beneficiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_beneficiary()
        {
            this.tbl_OandM = new HashSet<tbl_OandM>();
        }
    
        public int BeneficiaryID { get; set; }
        public string WorkOrderNo { get; set; }
        public string PumpType { get; set; }
        public string systemCapacity { get; set; }
        public string BeneficiaryName { get; set; }
        public string FatherName { get; set; }
        public string ContactNo { get; set; }
        public string Village { get; set; }
        public string Block { get; set; }
        public string District { get; set; }
        public string Aadhar { get; set; }
        public string Caste { get; set; }
        public string category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OandM> tbl_OandM { get; set; }
    }
}
