//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGSolar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StockRequest
    {
        public int Request_ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Status { get; set; }
    }
}
