//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGSolar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_itemstock
    {
        public long itemstockId { get; set; }
        public Nullable<long> Itemcode { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
