
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CGSolar
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_InventoryStock
{

    public long InventoryID { get; set; }

    public string VendorName { get; set; }

    public string Item { get; set; }

    public Nullable<int> quantity { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public Nullable<decimal> Tax { get; set; }

    public string BillNo { get; set; }

    public Nullable<System.DateTime> BillDate { get; set; }

}

}
